### PR TITLE
Fix Windows Build CMP0135 Policy Deprecation

### PR DESCRIPTION
**Pull request by ikelly963**
Addresses #522 

Regarding this Policy: https://cmake.org/cmake/help/latest/policy/CMP0135.html
Setting Policy: https://cmake.org/cmake/help/latest/command/cmake_policy.html#setting-policies-explicitly

- [x] I've read and followed [CONTRIBUTING.md](https://github.com/objectbox/objectbox-dart/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by ikelly963** [comment]
First time contributing to a public GitHub repo. Please let me know if I need to do something additional.

**Comment by greenrobot-team** [comment]
Thank you! I'll have a look when I have time.

For me: from a first look the used option is not added until 3.24, but the minimum supported CMake is lower. Check how that works on older versions. Also the docs note that [enabling specific policies is discouraged](https://cmake.org/cmake/help/latest/command/cmake_policy.html#setting-policies-explicitly:~:text=While%20setting%20policies%20individually%20is%20supported%2C%20we%20encourage%20projects%20to%20set%20policies%20based%20on%20CMake%20versions).

**Comment by ikelly963** [comment]
Ok, great. I'll take a look at those docs and figure out why these tests are failing later, potentially today.

**Comment by greenrobot-team** [comment]
@ikelly963 Don't worry about that. `pana` fails because I need to still adjust the threshold and `coverage` just has no permission to upload the report because this is a branch outside of this repo.

**Comment by greenrobot-team** [comment]
The Flutter folks have a better fix. But I'm not sure it's still needed. See https://github.com/objectbox/objectbox-dart/issues/522#issuecomment-1849712951

**Pull request closed without merging**
