### PR TITLE
Box - change constructor to factory, reuse a single FlatBuffers builder instance

### PR DESCRIPTION
**Pull request by vaind**

### CODE REVIEW

**Review by greenrobot-team — COMMENTED** [review]
LGTM. But isn't (some) entity data now kept around in memory for each Box until a Store is closed? E.g. memory usage increases with each new (used) Box instance, no?

**Comment by vaind** [comment]
> memory usage increases with each new (used) Box instance

Correct, but there's only a single instance per entity, so I figured that should be fine?

**Comment by greenrobot-team** [comment]
> > memory usage increases with each new (used) Box instance
> 
> Correct, but there's only a single instance per entity (type), so I figured that should be fine?

Just wanted to mention it figuring esp. on mobile memory usage is a concern.

**Comment by vaind** [comment]
> keep the buffer if below 64 KB 

done and merged

**Pull request merged**
