### PR TITLE
Use ffigen for C-API bindings

### LINKED ISSUE #139: Clean up signatures.dart & bindings.dart
`signatures.dart` contains C-API signatures and those are used in DynamicLibrary lookup in `bindings.dart`. Those files have became a little large and repetitive. Let's think about how they can be cleaned up. Some ideas:

* use typedefs for common signatures for different "classes", like store, box, ...
* maybe rename "bindings" variable to something shorter, e.g. I like Go's `C.`
* maybe drop the `obx_` prefix

### PR DESCRIPTION
**Pull request by vaind**
Part of #139 - switches from manual binding definitions to `ffigen` generated code

### CODE REVIEW

**Comment by vaind** [comment]
@greenrobot-team you can have a first look when it works for you. Tests crash at the moment but I don't expect many changes to get it fixed.

**Comment by greenrobot-team** [comment]
Won't be able to complete my review until I'm back. Anyhow, most of what I've seen of the first commit seems straight forward.

**Comment by Buggaboo** [comment]
You might want to check the size of the pointers. They should be machine word size. Struct padding (I assume no packing is applied) could also be an issue.

Really cool tool. I didn't know about it until now. I tried writing my own this summer. I guess I could throw that away now.

**Comment by vaind** [comment]
> You might want to check the size of the pointers. They should be machine word size, unless instructed differently to the compiler :/ 

Thanks, I'm aware of that. I had to do some patching (not committed yet) [until it's resolved in ffigen](https://github.com/dart-lang/ffigen/issues/7#issuecomment-724627790)

**Comment by vaind** [comment]
> It's +10,112 −1,483 LoC and I assume the generated code is most of that. Can you give a high level explanation why it's almost +9K net? Maybe some example?

Yes, most of it is the generated code, the (hopefully temporary) patch file & objectbox.h, 9777 lines added altogether.

image

The generated code is a lot larger then our manual code because it doesn't use templates (generics) which we used to reduce the amount of manual work (though it has made the code quite a bit less readable) and it is more type safe (all pointers now have types, like `Pointer<OBX_Store>` instead of the original `Pointer<Void>`. Also, it's actually complete (with the exception of `obx_cursor_*` which I've excluded for now (unused), as opposed to the original binding code where we've only defined what we needed. 

-----------------

> Could you point us to that patch you did?

https://github.com/objectbox/objectbox-dart/pull/146/files#diff-fdd27307bfa2cd39c097a0ca82b66dfce50d199482400073ea7b37399e74ff22

> Did you test this on a 32 bit system (in addition to 64 bit ofc); e.g. Android?

Yes, tested the example app on the 32-bit android. We can't run our complete test-suite on device [yet](https://github.com/objectbox/objectbox-dart/issues/81).

**Pull request merged**
