### PR TITLE
Attach Dart finalizer to Store to close on Flutter hot restart

### PR DESCRIPTION
**Pull request by greenrobot-team**
Proposed solution for #387

We welcome feedback, e.g. if this has any unforeseen side-effects within a Flutter app.

_Note: this mirrors an internal merge request._

### CODE REVIEW

**Comment by richard457** [comment]
After using the latest version which is believed to solve this issue now issue is back 
```
Abort message: 'terminating'
    rax 0000000000000000  rbx 000076b6153004f8  rcx ffffffffffffffff  rdx 0000000000000006
    rsi 000000000000125d  rdi 00000000000011c5
    r8  0000000000000000  r9  000076b6890a6090  r10 0000000000000008  r11 0000000000000206
    r12 000000000000125d  r13 0000000000000006  r14 000076b655a698a2  r15 000076b6152ffca0
    cs  0000000000000033  ss  000000000000002b
    rip 000076b685a76b67  rbp 0000000000000019  rsp 000076b6152ffba8  eflags 0000000000000206
backtrace:
    #00 pc 000000000008db67  /system/lib64/libc.so (tgkill+7)
    #01 pc 000000000008a601  /system/lib64/libc.so (pthread_kill+65)
    #02 pc 0000000000030241  /system/lib64/libc.so (raise+17)
    #03 pc 000000000002877d  /system/lib64/libc.so (abort+77)
    #04 pc 00000000002902cb  /data/app/rw.flipper-1/lib/x86_64/libobjectbox-jni.so
    #05 pc 0000000000290339  /data/app/rw.flipper-1/lib/x86_64/libobjectbox-jni.so
    #06 pc 000000000028d302  /data/app/rw.flipper-1/lib/x86_64/libobjectbox-jni.so
    #07 pc 000000000028d2a7  /data/app/rw.flipper-1/lib/x86_64/libobjectbox-jni.so (_ZSt9terminatev+55)
    #08 pc 00000000001e0324  /data/app/rw.flipper-1/lib/x86_64/libobjectbox-jni.so
    #09 pc 00000000001e0a24  /data/app/rw.flipper-1/lib/x86_64/libobjectbox-jni.so
    #10 pc 0000000000095476  /data/app/rw.flipper-1/lib/x86_64/libobjectbox-jni.so
    #11 pc 0000000000090c30  /data/app/rw.flipper-1/lib/x86_64/libobjectbox-jni.so
    #12 pc 0000000000094b17  /data/app/rw.flipper-1/lib/x86_64/libobjectbox-jni.so
    #13 pc 0000000000089771  /system/lib64/libc.so (_ZL15__pthread_startPv+177)
    #14 pc 00000000000299eb  /system/lib64/libc.so (__start_thread+11)
    #15 pc 000000000001ca65  /system/lib64/libc.so (__bionic_clone+53)

```

**Comment by richard457** [comment]
@greenrobot-team @greenrobot @vaind

**Comment by richard457** [comment]
It happen when I restart the application, I got the info from the vs code terminal console.

**Comment by greenrobot-team** [comment]
@richard457 I suggest to create a new issue and fill out the template as best possible! Otherwise this is impossible for us to reproduce.

**Pull request merged**
