### PR TITLE
Work in Progress: Packages Analysis CI

### PR DESCRIPTION
**Pull request by GregorySech**
I've split the packages so that pana will not consider the generator inside the main package.

Also I've renamed the examples folder in `example` so that the "pre deploy" sh script I'm making will just have to copy all the shared files (example, changelog, readme, license) into the two packages before they get deployed.

Right now I'm unable to build the dev branch correctly (even before my changes).
So all of this is pretty much untested.
I keep getting this error whenever I run `flutter pub run build_runner build`
```
[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
[SEVERE] /Users/gregorysech/flutter/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.2/lib/src/utf8.dart:21:20: Error: Expected 0 type arguments.class Utf8 extends Struct<Utf8> {                   ^/Users/gregorysech/flutter/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.2/lib/src/utf16.dart:14:21: Error: Expected 0 type arguments.class Utf16 extends Struct<Utf16> {                    ^/Users/gregorysech/flutter/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.2/lib/src/utf8.dart:24:35: Error: Type argument 'Utf8' doesn't conform to the bound 'NativeType' of the type variable 'T' on 'Pointer'. - 'Utf8' is from 'package:ffi/src/utf8.dart' ('/Users/gregorysech/flutter/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.2/lib/src/utf8.dart'). - 'NativeType' is from 'dart:ffi'.Try changing type arguments so that they conform to the bounds.  static int strlen(Pointer<Utf8> string) {                                  ^/Users/gregorysech/flutter/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.2/lib/src/utf8.dart:39:40: Error: Type argument 'Utf8' doesn't conform to the bound 'NativeType' of the type variable 'T' on 'Pointer'. - 'Utf8' is from 'package:ffi/src/utf8.dart' ('/Users/gregorysech/flutter/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.2/lib/src/utf8.dart'). - 'NativeType' is from 'dart:ffi'.Try changing type arguments so that they conform to the bounds.  static String fromUtf8(Pointer<Utf8> string) {                                       ^/Users/gregorysech/flutter/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.2/lib/src/utf8.dart:54:30: Error: Type argument 'Utf8' doesn't conform to the bound 'NativeType' of the type variable 'T' on 'Pointer' in the return type. - 'Utf8' is from 'package:ffi/src/utf8.dart' ('/Users/gregorysech/flutter/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.2/lib/src/utf8.dart'). - 'NativeType' is from 'dart:ffi'.Try changing type arguments so that they conform to the bounds.  static Pointer<Utf8> toUtf8(String string) {                             ^/Users/gregorysech/flutter/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.2/lib/src/utf16.dart:22:32: Error: Type argument 'Utf16' doesn't conform to the bound 'NativeType' of the type variable 'T' on 'Pointer' in the return type. - 'Utf16' is from 'package:ffi/src/utf16.dart' ('/Users/gregorysech/flutter/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.2/lib/src/utf16.dart'). - 'NativeType' is from 'dart:ffi'.Try changing type arguments so that they conform to the bounds.  static Pointer<Utf16> toUtf16(String s) {                               ^lib/src/common.dart:18:33: Error: Method not found: 'Pointer.allocate'.  var majorPtr = Pointer<Int32>.allocate(), minorPtr = Pointer<Int32>.allocate(), patchPtr = Pointer<Int32>.allocate();                                ^^^^^^^^lib/src/common.dart:18:71: Error: Method not found: 'Pointer.allocate'.  var majorPtr = Pointer<Int32>.allocate(), minorPtr = Pointer<Int32>.allocate(), patchPtr = Pointer<Int32>.allocate();                                                                      ^^^^^^^^lib/src/common.dart:18:109: Error: Method not found: 'Pointer.allocate'.  var majorPtr = Pointer<Int32>.allocate(), minorPtr = Pointer<Int32>.allocate(), patchPtr = Pointer<Int32>.allocate();                                                                                                            ^^^^^^^^lib/src/model.dart:20:13: Error: Inferred type argument 'Utf8' doesn't conform to the bound 'NativeType' of the type variable 'T' on 'Pointer'. - 'Utf8' is from 'package:ffi/src/utf8.dart' ('/Users/gregorysech/flutter/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.2/lib/src/utf8.dart'). - 'NativeType' is from 'dart:ffi'.Try specifying type arguments explicitly so that they conform to the bounds.        var entityUtf8 = Utf8.toUtf8(currentEntity.name);            
```

### CODE REVIEW

**Comment by GregorySech** [comment]
There are still a couple of problems.
The first one is that there are some compilation errors in the objectbox package. My fork's actions run with no problems and the output is [here](https://github.com/GregorySech/objectbox-dart/runs/268784568).
The second one is about the analysis actions not being able to find some resource but I have no clue of what is it about...

On a brighter note in my fork the analysis jobs took a little less than 3 minutes each.

**Comment by axel-op** [comment]
Two things here:

1. You can remove lines [8-9](https://github.com/objectbox/objectbox-dart/blob/3d4c4735686955f403b02df4a869ddb222c302b8/.github/workflows/analysis.yml#L8) and [19-20](https://github.com/objectbox/objectbox-dart/blob/3d4c4735686955f403b02df4a869ddb222c302b8/.github/workflows/analysis.yml#L19) of your `.github/workflows/analysis.yml` file as they're completely unnecessary and add almost 40 seconds to build time for nothing. I mean these lines:
```yaml
    container:
      image:  google/dart:latest
```

2. The GitHub error here is due to GitHub that applies restrictions for security reasons on token's permissions, as the workflow file has not been merged yet into the repository. In other words, the token can't be used on this repo while the file hasn't been merged in.

**Comment by vaind** [comment]
I had a look and I had to reimplement the changes (renames & path fixes around the code) manually in order to make it work correctly.

AFAICT this PR can now really be only about the CI script. Unfortunately, there's the outstanding issue with queries, also discussed here: https://github.com/objectbox/objectbox-dart/issues/43 

I'm not sure how we can resolve that at the moment :/

**Comment by GregorySech** [comment]
I should be able to give the PR more attention in the weekend. Sorry

**Comment by vaind** [comment]
no worries, thanks for the contributions so far :)

**Comment by greenrobot-team** [comment]
Is this still something worth pursuing?

**Comment by GregorySech** [comment]
Sorry I cannot follow this PR and I will not work with Flutter for a while. I'll close the PR.

**Pull request closed without merging**
