### PR TITLE
Web support vol.1

### PR DESCRIPTION
**Pull request by vaind**
Part of #185

* Shuffles stuff around and uses conditional exports to add "support" JS/web. 
* Actual support not implemented yet, just won't import anything not available on JS/web platforms, thus the analyzer thinks package supports it.
* **I've done my best to make this reviewable commit by commit. Ignore "Files changed" tab in the PR, it doesn't show up the moved files properly.**

### TODO:
* [ ] Don't merge as is, we should actually add some import that breaks web support before releasing, to avoid user confusion. E.g. add the following code to `lib/objectbox.dart`: `import 'dart:ffi';`
* [ ] ALso for the same reason don't merge the CI commit, it's here just so that we don't break the web support unintentionally when changes are made before merging

### CODE REVIEW

**Comment by greenrobot-team** [comment]
Note: Dart docs about conditional imports https://dart.dev/guides/libraries/create-library-packages#conditionally-importing-and-exporting-library-files

**Comment by vaind** [comment]
> Note: Dart docs about conditional imports https://dart.dev/guides/libraries/create-library-packages#conditionally-importing-and-exporting-library-files

Make sure to read the linked issue in case you haven't (the link's there)

**Comment by greenrobot-team** [comment]
> Make sure to read the linked issue in case you haven't (the link's there)

Thanks! Only read replies today, so missed it...

**Review by greenrobot-team — COMMENTED** [review]
LGTM, no obvious issues, still builds and tests run on my Windows setup.

I'd imagine not having an "interface" or stub implementation could lead to deviations in the two APIs. Does the compiler somehow check the APIs match between implementations? But I guess tests would uncover this quickly.

Also having to copy some of the generated constants is a step back, but I don't see another solution as well.

**Pull request merged**
