### PR TITLE
WIP - Property query

### PR DESCRIPTION
**Pull request by Buggaboo**
#48 I need help with the tests, and some feedback wrt to the design.

My count test is broken. What am I doing wrong?

Please, don't merge yet.

### CODE REVIEW

**Comment by vaind** [comment]
> My count test is broken. What am I doing wrong?

Couldn't find anything... current dart v2.5.2 still fails to properly show capture the exception (issue #1)  and the lib doesn't compile with the latest dev v2.6 which should have the issue resolved and show you the proper error. I'll try to have a look at the errors given by 2.6 tomorrow and let you know.

**Comment by vaind** [comment]
Regarding the design, I'll have a better look tomorrow. Just one thing that occurred to me would be nice:
```
final queryInt = query.property(tLong); // lose the type in the method name
int sum = queryInt.sum();
```
Maybe we could handle it with the type system somehow - using generics on `QueryProperty` and getting the generic type out of it in the declaration of `property()` method

**Comment by Buggaboo** [comment]
> Regarding the design, I'll have a better look tomorrow. Just one thing that occurred to me would be nice:
> 
> ```
> final queryInt = query.property(tLong); // lose the type in the method name
> int sum = queryInt.sum();
> ```
> 
> Maybe we could handle it with the type system somehow - using generics on `QueryProperty` and getting the generic type out of it in the declaration of `property()` method

Done.

**Comment by Buggaboo** [comment]
> > My count test is broken. What am I doing wrong?
> 
> Couldn't find anything... current dart v2.5.2 still fails to properly show capture the exception (issue #1) and the lib doesn't compile with the latest dev v2.6 which should have the issue resolved and show you the proper error. I'll try to have a look at the errors given by 2.6 tomorrow and let you know.

It might be a bug wrt to signedness (e.g. UintX vs IntX), but I'm not sure.

**Comment by vaind** [comment]
With all the errors you're getting, it seems something is fundamentally wrong. I'd maybe wait for 2.6 before spending too much time trying to debug it. With a proper error message, it should be straightforward.

**Comment by Buggaboo** [comment]
> With all the errors you're getting, it seems something is fundamentally wrong. I'd maybe wait for 2.6 before spending too much time trying to debug it. With a proper error message, it should be straightforward.

Ugh. Can you please start a *dev-2.6* branch? I'll start hacking that instead. This is driving me crazy.

**Comment by Buggaboo** [comment]
I retraced my steps and reimplemented the cstructs used in the `find` calls without `Struct`, like we used to with `OBX_array_ids`. And I still have the same error. Something is fundamentally broken.

**Comment by Buggaboo** [comment]
Since 2.6 is the new stable version. I'm closing this one.

**Pull request closed without merging**
